menu:
    shop: Bolt
    products: Termékek
    tags: Címkék
    orders: Rendelések
    stats: Bolt
    books: Könyvek

    postal_fees: Szállítás módja
    country_postal_fees: A szállítás helye és módja
    sort_shop_products: Termékek rendezése a főoldalon
frontend:
    shop:
        cart:
            header: Kosár tartalma
            product: Termék
            price: Ár
            amount: Összeg
            together: Összesen fizetendő
            price_with_vat: Összesen fizetendő
            continue_with_shopping: Folytatom a vásárlást
            order: Fizetés
            empty_cart: Jelenleg nincs termék a kosaradban.
            confirm_order: Fizetés
            messages:
                item_added_to_cart: "<strong>%name%</strong> a kosaradba került."
                item_not_available: "<strong>%name%</strong> nem elérhető."
                items_removed_from_cart: 'Egyes termékek (<strong>%name%</strong>) el lettek távolítva a kosárból</a>.'
                items_removed_from_cart_reason_sold_out: 'Egyes termékek (<strong>%name%</strong>) el lettek távolítva a kosárból, mivel elfogytak.'
        checkout:
            order: Fizetési adatok
            payment_method: Fizetési mód
            contact_information: Kapcsolat információ
            login: Bejelentkezés
            shipping_address: Szállítási cím
            license_address: Licensz cím
            shipping_method: Szállítási mód
            billing_address: Számlázási cím
            for_free: Ingyenes
            choose_payment_method: Válasszon Fizetési módot.
            warnings:
                unable_to_login_with_password: 'Ezzel a jelszóval nem tudtunk beléptetni'
        default:
            filter: Szűrés
            all: Mind
            add_to_cart: Kosárba
            sold_out: elkelt
        error:
            title: "Hiba"
        success:
            title: "Köszönjük!"
            header: "Köszönjük!"
            payment_successful: "Sikeres fizetés."
        show:
            title: "%product_name%"
            add_to_cart: Kosárba
            sold_out: elkelt

    orders:
        my_orders: Rendeléseim
        my_books: Könyveim
        day: Nap
        order_number: Rendelés száma
        price: Ár
        status: Állapot
        invoices: Számlák
        postal_fee: Szállítási díj
        no_orders: Nincs rendelés.
        no_books: Nincs könyved.
        visit_eshop: Látogass el a boltunkba.
        title: Cím
        preparing_download: Letöltés előkészítése
data:
    products:
        placeholder:
            price: pl. 13.99
            description: pl. Ez a termék nagyszerű
            name: pl. bambusz póló
            code: pl. bambusz-polo
            user_label: pl. bambusz póló
            catalog_price: pl. 15.99
            sorting: Az első helyre
            ean: pl. 8580000000000
            image_url: pl. http://dennikn.sk/images/shop.jpg
            og_image_url: pl. http://dennikn.sk/images/shop.jpg
            images: pl. http://dennikn.sk/images/shop.jpg
        errors:
            name: A 'Név' tétel kitöltése kötelező
            og_image_url: A 'OG:image URL' tétel kitöltése kötelező
            catalog_price_float_positive: Az 'Árjegyzék szerinti ár' tétel nem lehet negatív szám
            ean13: Az EAN kódnak 13 jegyűnek kell lenni
            template_property: A '%s' tétel kitöltése kötelező
            image_url: A ' Fénykép URLje' tétel kitöltése kötelező
            description: A 'Leírás' tétel kitöltése kötelező
            price_float_positive: Az 'Értékesítési ár áfával' tétel nem lehet negatív szám
            price_required: Az 'Értékesítési ár áfával' tétel kitöltése kötelező
            code: Az 'Azonosító' tétel kitöltése kötelező
        fields:
            name: Név
            code: Azonosító
            price: Értékesítési ár áfával
            catalog_price: Árjegyzék szerinti ár
            vat: áfa
            user_label: Nyilvános leírás
            shop: Bolti értékesítés
            tags: Címkék
            og_image_url: OG:image URL
            description: Leírás
            ean: EAN-vonalkód
            image_url: A fénykép URL címe
            images: Fényképgaléria
            distribution_center: Disztribúciós központ
            visible: Címlapra helyezés
            unique_per_user: Kizárólag a felhasználó számára
            has_delivery: Postaköltség hozzáadása
            bundle: Csomag
            sorting: Termék besorolása a következő mögé
            template_id: Sablon
            bundles: Csomagok
            bundle_items: A csomag tételei
            created_at: Létrehozva
            stock: A raktáron található tételek száma
            available_at: 'Hozzáférhető:'
            shop_settings: Bolti beállítások
        descriptions:
            image_url: 'Kérjük, az alábbi képfelbontást használja: 856px * 565px'
            user_label: Csak a számlán szokás feltüntetni
            images: A fényképek URLjeinek listája. Minden egyes URL új sorban található.
