menu:
    shop: Shop
    products: Products
    tags: Tags
    orders: Orders
    stats: Shop
    books: Books
    postal_fees: Delivery methods
    country_postal_fees: Countries and delivery methods

data:
    products:
        fields:
            name: Name
            code: Identifier
            price: Shop price with VAT
            catalog_price: Basic price
            vat: VAT
            user_label: Label
            shop: Sell in shop
            sorting: Place after
            tags: Tags
            description: Description
            ean: EAN code
            image_url: Photo URL
            og_image_url: OG:image URL
            images: Photogallery
            distribution_center: Distribution center
            visible: Place on homepage
            unique_per_user: Unique per user
            has_delivery: Add postal fee
            template_id: Template
            bundle: Bundle
            bundle_items: Bundle items
            bundles: Bundles
            created_at: Created at
            stock: Stock count
            available_at: Date of Availability
            shop_settings: Shop settings
        placeholder:
            name: eg. Bamboo T-shirt
            code: eg. bamboo-shirt
            user_label: eg. Bamboo T-shirt
            price: eg. 13.99
            catalog_price: eg. 15.99
            sorting: First position
            description: This product is cool
            ean: eg. 8580000000000
            image_url: eg. http://dennikn.sk/images/shop.jpg
            og_image_url: eg. http://dennikn.sk/images/shop.jpg
            images: eg. http://dennikn.sk/images/shop.jpg
        descriptions:
            user_label: Used only on invoice
            image_url: Size of picture 856px * 565px
            images: List of image URLs. Each URL is on new line.
        errors:
            name: Field 'Name' is required
            code: Field 'Code' is required
            description: Field 'Description' is required
            image_url: Field 'Photo URL' is required
            og_image_url: Field 'OG:image URL' is required
            price_required: Field 'Shop price with VAT' is required
            price_float_positive: Field 'Shop price with VAT' must be a non-negative number
            catalog_price_float_positive: Field 'Basic price' must be a non-negative number
            ean13: EAN code must be 13 characters
            template_property: Field '%s' is required
            vat: VAT is required
            not_stored_to_distribution_center: 'Unable to save product to distribution center.'
            stock_required: Field 'Stock count' is required
            stock_positive: Field 'Stock count' must be a non-negative number
    tags:
        fields:
            name: Name
            code: Code
            icon: Icon
            visible: Place on homepage
            products: Number of products
            sorting: Place tag after
        placeholder:
            name: SuperTag
            code: super-tag
            icon: fa-tag
            sorting: To the first position
        descriptions:
            code: Code will be used in shop URL for products with given tag.
            icon: Choose from FontAwesome. For N logo use dennikn.
        errors:
            name: Field 'Name' is mandatory.
            icon: Field 'Icon' is mandatory.
    postal_fees:
        fields:
            title: Name
            code: Identifier
            used_count: Used
            amount: Amount
    country_postal_fees:
        fields:
            country_id: Country
            postal_fee_id: Delivery method
            default: Default
            active: Active
            sorting: Sorting
            condition: Condition
            condition_value: Value
    orders:
        statuses:
            paid: Paid
            not_sent: Not sent
            pending: Pending
            confirmed: Confirmed
            sent: Sent
            delivered: Delivered
            returned: Returned

admin:
    component:
        avg_product_payment_widget:
            avg_product_payment: Average payments for products
        payment_items_list_widget:
            product_deleted: Product was already removed from the system
    products:
        default:
            header: Products
            new: Create product
            admin_filter_form:
                text:
                    placeholder: 'Name / Identifier / Label / Price'
                tags: Tags

        new:
            title: New product
            back: Back to the list
        show:
            back: Back to the list
            edit: Edit product
            sold_count: Sold count
            distribution:
                label: Distribution
                amountSpent: How much paid before buying the product
                paymentCounts: How many payment made before buying the product
                shopCounts: How many orders in shop made before buying the product
                shopDays: 'When was the last time user made shop order (in days before buying the products)'
                neverBoughtShop: Never bought anything in shop
        edit:
            title: Edit product
            back: Back to listing
        messages:
            no_bundles_message: This product is not assigned to any bundle.
            no_bundle_items_message: "This bundle doesn't contain any items."
            product_not_found: "Selected product doesn't exist."
            product_created: Product was created.
            product_updated: Product was updated.
            product_deleted: Product '%product%' was deleted.
        users_list:
            back: Back
            email: Email
            source: Source
            state: State
            created_at: Created at
            invoice: Invoice
            institution: Institution
            admin: Administrator
        stats:
            product: Product
            today: Today
            yesterday: Yesterday
            seven_days: 7 days
            this_month: This month
            last_month: Last month
            all_stats: All
            sold_products: Sold products
            sold_products_in_time: Sold products time histogram
            count: Number of pieces
            amount: Total money
            total: Total
            modes:
                all: All
                sold: Sold
                gifted: Gifted
            form:
                mode: Sale type
                filter: Filter
    tags:
        default:
            header: Tags
            new: Create tag
        new:
            title: New tag
            back: Back to the list
        edit:
            title: Edit tag
            back: Back to the list
        messages:
            tag_created: Tag was created.
            tag_updated: Tag was updated.
            tag_deleted: Tag was deleted.
            tag_indelible: "The tag cannot be deleted, it is still in use."
        delete:
            title: Delete tag
            tooltip: The tag is still in use
    orders:
        default:
            header: Orders
            totalCount: total
            filteredCount: filtered
            empty: There is no records matching the filter
            fields:
                variable_symbol: Variable symbol
                products: Products
                sum: Sum
                email: Email
                order_state: Order State
                payments: Payments
                created_at: Created at
                actions: Actions
                filter: Filter
                cancel_filter: Cancel filter
                order_id_vs: 'OrderID / VS'
                payment_state: Payment State
            warnings:
                order_for_payment_exists: 'Order assigned to payment already exists, we have redirected you to the order.'
        new:
            header: New order
            for_payment: to payment
            contact_details: Contact details
            shipping_option: Shipping options
            shipping_address: Shipping address
            license_data: License data
            billing_address: Billing address
            product: Product
            price: Sum
            amount: Amount
            together: Total
            price_with_vat: Price with VAT
            sum_on_payment: Payment amount
            warnings:
                payment_sum_not_equal: "The payment amount is not the same as the sum of the products and shipping charges."
                order_will_override_sum_on_payment: "Creating an order will overwrite the amount on your payment to"
            create_order: Create order
        show:
            header: Order
            back: Back
            shipping_address: Shipping address
            licence_address: Licence address
            billing_address: Billing address
            fields:
                created_at: Created At
                amount: Price
                email: User
                status: Status
                payment_status: Payment status
                note: Note
                address:
                    name: Name
                    street: Street
                    city: City
                    zip: ZIP
                    company_name: Company name
                    ico: Buyer ID
                    dic: Tax ID
                    icdph: Vat ID
                    phone_number: Phone Number
            products:
                header: Ordered products
                fields:
                    name: Name
                    price: Price
                    count: Count
    postal_fees:
        default:
            header: Delivery methods
    country_postal_fees:
        default:
            header: Countries and delivery methods
            form_header: Delivery method
            submit: Save delivery method
            close: Close
            successfully_added: Delivery method was successfully saved
            successfully_deleted: Delivery method was successfully removed
            error_already_exists: The selected delivery method is already added
            sorting_required: Field 'Sorting' is required
            condition_value_required: Field 'Value' is required
        conditions:
            products_sum:
                label: Sumary of products in the cart
                validation_integer: Sumary of products has to be a numeric value
                validation_min: Sumary of products has to be a positive value
            user_segment:
                label: Segment of users
                message: "You have free delivery today because you are our subscriber."
    distribution:
        shopCounts: How many orders in shop made before the payment
        shopDays: How many days passed since last order in shop
        neverBoughtShop: Never bought anything in shop
        email: E-mail
        source: Source
        status: Status
        invoice: Invoice
        created_at: Created at
        back_to_funnel: Back to funnel
        warning: Distribution is out of date. Please run `sales-funnel:distributions` command.

    total_user_payments:
        for_shop_payments: "{1}payment in shop|[2,Inf]payments in shop"

    dashboard:
        title: Shop stats

    scenarios:
        actual_order_status:
            label: Actual order status
        order_status_on_scenario_enter:
            label: Order status at the time of entering the scenario
        has_product_with_template_name:
            label: Has product with template name
        has_product_with_distribution_center:
            label: Has product with distribution center

frontend:
    shop:
        cart:
            header: Shopping cart
            product: Product
            price: Price
            amount: Amount
            together: Total
            price_with_vat: Price with VAT
            continue_with_shopping: Back to shopping
            order: order
            empty_cart: Shopping cart is empty.
            confirm_order: Confirm order
            messages:
                item_added_to_cart: "Item <strong>%name%</strong> was added to cart."
                item_not_available: "Item <strong>%name%</strong> is not available."
                item_more_not_available: "No more pieces of item <strong>%name%</strong> available."
                item_already_purchased: 'Item <strong>%name%</strong> has already been purchased. Download link can be found <a href="%link%" class="link">in your profile</a>.'
                items_removed_from_cart: 'Some items (<strong>%name%</strong>) were removed from the cart, because you already purchased them. Download links can be found <a href="%link%" class="link">in your profile</a>.'
                items_removed_from_cart_reason_sold_out: 'Some items (<strong>%name%</strong>) were removed from the cart, since they are sold out.'
                items_removed_from_cart_reason_little_stock: 'Some items (<strong>%name%</strong>) have had their number of pieces reduced because there are not enough in stock.'
        checkout:
            order: Order
            payment_method: Payment method
            contact_information: Contact information
            sign_under_different_account: "sign in with another account?"
            forgot_password: "forgot your password?"
            login: Sign in
            shipping_address: Shipping address
            license_address: License address
            shipping_method: Shipping method
            billing_address: Billing address
            for_free: For free
            postal_fee: Shipping
            choose_payment_method: Vyber spôsob platby.
            fields:
                email_required: Field Email is required.
                pass_required: Field Password is required.
                account_exists: 'Account with entered email already exists, please login with password'
                phone_number: 'Phone Number'
                phone_number_placeholder: 'E.g. +421 908 123 456'
                phone_number_required: 'Field Phone Number is required.'
                phone_number_min_length: 'Phone Number has to be at least 9 characters long.'
                phone_number_wrong_format: 'Phone number must be in the international format (e.g.: +421 908 123 456).'
                want_invoice: I want invoice
                same_shipping: 'Billing address same as shipping address'
                choose_shipping_method: 'Choose shipping method.'
                first_name: First Name
                first_name_required: 'Field First Name is required.'
                last_name: Last Name
                last_name_required: 'Field Last Name is required.'
                street: Street
                street_required: 'Field Street is required.'
                street_min_length: 'Field Street has to be at least 3 characters long'
                number: Number
                number_required: 'Field Number is required.'
                city: City
                city_required: 'Field City is required.'
                zip_code: Zip Code
                zip_code_required: 'Field Zip Code is required.'
                zip_code_invalid: 'The zip code field should contain exactly 5 numbers and must be in the format: XXX XX (e.g.: 841 07).'
                country: Country
                company_name: 'Company Name'
                company_name_required: 'Field Company Name is required.'
                company_id: 'Company ID'
                company_id_placeholder: 'E.g. 12345678'
                company_tax_id: 'Company Tax ID'
                company_tax_id_placeholder: 'E.g. 2020123456'
                company_vat_id: 'Company VAT ID'
                company_vat_id_placeholder: 'E.g. SK2020123456'
                toc: 'I agree with <a href="%link%" class="link" target="_blank">terms and conditions</a>'
                toc_required: 'You have to agree with terms and conditions'
                login: Log in
            warnings:
                unable_to_login_with_password: 'Unable to log in using provided password'
                unable_to_create_user: 'Unable to create user.'
                invalid_email: "This email is not valid."
                email_registered: "E-mail is already registered, please enter your password."
        default:
            filter: Filter
            all: All
            add_to_cart: add to cart
            sold_out: sold out
        error:
            title: "Error : E-shop Denník N - we only sell what we read"
            text: '<strong>Error:</strong> Unfortunately your payment was not successful. Please try again later or contact our support at <a href="mailto:%contactEmail%" class="link">%contactEmail%</a>.'
        success:
            title: "Thank you! : E-shop Denník N - we only sell what we read"
            header: "Thank you!"
            payment_successful: "Your payment was successful."
            list_of_books_to_download: "List of books to download"
        show:
            title: "%product_name% : E-shop Denník N - we only sell what we read"
            available_at: 'The product will be available at %available_at%, we will send it the next day.'
            add_to_cart: add to cart
            sold_out: sold out

    orders:
        my_orders: My orders
        my_books: My books
        day: Day
        order_number: Order number
        price: Price
        status: Status
        invoices: Invoices
        postal_fee: Postal fee
        no_orders: You have no orders.
        no_books: You have no books bought.
        visit_eshop: Visit our eshop.
        visit_eshop_ebooks: "You can buy e-books at %shop_url%, all your books will be available here."
        title: Title
        preparing_download: Preparing download

    components:
        free_shipping_progress_bar:
            message: "For free delivery buy products for another <strong>%amount%</strong>."
            reached_message: "You order reached <strong>%amount%</strong>, you have <strong>free delivery</strong>."

data_provider:
    delete:
        active_order: User has/had a recent order and cannot be deleted.
        unexpected_configuration_value: "Unexpected configuration value 'Users -> Count of days to check'"
    payment_form_data:
        products_from_eshop: "Products from e-shop:"
        products_from_eshop_desc: "Warning: after product selection, it's required to enter number of purchased products."
        products_from_eshop_readonly: "It's not possible to edit products, order has already been created."
    payment_item_types_filter:
        key:
            product: Shop

config:
    category: Shop
    shop_host:
        name: Shop URL
        description: 'URL of shop (in case its running on separate domain; e.g. <code>shop.crm.press</code>)'
    shop_header_block:
        name: "Code in shop's header"
        description: 'Any optional code (e.g. Google Analytics) that should be injected to the head of shop layout'
    shop_og_image_url:
        name: OG:image URL
        description: 'Full URL to the image (e.g. <code>/layouts/admin/images/logo_with_text.svg</code>)'
    shop_terms_and_conditions_url:
        name: URL T&C
        description: 'URL where the general terms and conditions are located (eg. <code>http://crm.press/terms-and-conditions/</code>)'
    shop_title:
        name: Shop title
        description: 'Custom shop title'
        value: 'E-shop Denník N - we only sell what we read.'
    users:
        category: Users
        prevent_anonymization:
            name: Prevent the anonymization of user with a recent order
            description: Will block the anonymization of user in the case of a recent order
        prevent_anonymization_within_days:
            name: Number of days to check
            description: 'The number of days to check since the last order. The setting is only considered if the "Prevent the anonymization of user with a recent order" option above is enabled.'

seeders:
    address_types:
        gift_subscription_type: Gift subscription
